
CREATE TABLE empleados (
    id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    apellido VARCHAR(50) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    dni INT UNSIGNED NOT NULL UNIQUE,
    alta DATE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

